---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: transaction-service
  namespace: bank-infra
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - transaction-service-app
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
