
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: transaction-service-pr
  namespace: bank-infra
  labels:
    app: transaction-service-app
spec:
  clusterReplicas: 2
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - sydney-cluster
      - melbourne-cluster
      - brisbane-cluster
