---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: transaction-service
  name: transaction-service-placement-1
  namespace: bank-infra
spec:
  clusterSelector:
    matchLabels:
      'environment': 'dev'
