---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mobile-simulator-app-latest
  namespace: bank-infra
spec:
  pathname: https://github.com/akiyamn/example-bank-rhacm.git
  type: GitHub
